// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: detection_tracking_pipeline.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SentTimestamp string                 `protobuf:"bytes,2,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_detection_tracking_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_detection_tracking_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_detection_tracking_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Data) GetSentTimestamp() string {
	if x != nil {
		return x.SentTimestamp
	}
	return ""
}

type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      string                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	SentTimestamp string                 `protobuf:"bytes,3,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_detection_tracking_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_detection_tracking_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_detection_tracking_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *FrameData) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *FrameData) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *FrameData) GetSentTimestamp() string {
	if x != nil {
		return x.SentTimestamp
	}
	return ""
}

type DataResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Payload           string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ReceivedTimestamp string                 `protobuf:"bytes,3,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	SentTimestamp     string                 `protobuf:"bytes,4,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_detection_tracking_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_tracking_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_detection_tracking_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *DataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *DataResponse) GetReceivedTimestamp() string {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return ""
}

func (x *DataResponse) GetSentTimestamp() string {
	if x != nil {
		return x.SentTimestamp
	}
	return ""
}

type Ack struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OriginalSentTimestamp string                 `protobuf:"bytes,2,opt,name=original_sent_timestamp,json=originalSentTimestamp,proto3" json:"original_sent_timestamp,omitempty"`
	ReceivedTimestamp     string                 `protobuf:"bytes,3,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	AckSentTimestamp      string                 `protobuf:"bytes,4,opt,name=ack_sent_timestamp,json=ackSentTimestamp,proto3" json:"ack_sent_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_detection_tracking_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_detection_tracking_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_detection_tracking_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ack) GetOriginalSentTimestamp() string {
	if x != nil {
		return x.OriginalSentTimestamp
	}
	return ""
}

func (x *Ack) GetReceivedTimestamp() string {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return ""
}

func (x *Ack) GetAckSentTimestamp() string {
	if x != nil {
		return x.AckSentTimestamp
	}
	return ""
}

var File_detection_tracking_pipeline_proto protoreflect.FileDescriptor

const file_detection_tracking_pipeline_proto_rawDesc = "" +
	"\n" +
	"!detection_tracking_pipeline.proto\x12\x19detection_tracking_system\"G\n" +
	"\x04Data\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12%\n" +
	"\x0esent_timestamp\x18\x02 \x01(\tR\rsentTimestamp\"m\n" +
	"\tFrameData\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\fR\tframeData\x12%\n" +
	"\x0esent_timestamp\x18\x03 \x01(\tR\rsentTimestamp\"\x96\x01\n" +
	"\fDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12-\n" +
	"\x12received_timestamp\x18\x03 \x01(\tR\x11receivedTimestamp\x12%\n" +
	"\x0esent_timestamp\x18\x04 \x01(\tR\rsentTimestamp\"\xb2\x01\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x126\n" +
	"\x17original_sent_timestamp\x18\x02 \x01(\tR\x15originalSentTimestamp\x12-\n" +
	"\x12received_timestamp\x18\x03 \x01(\tR\x11receivedTimestamp\x12,\n" +
	"\x12ack_sent_timestamp\x18\x04 \x01(\tR\x10ackSentTimestamp2\x82\x03\n" +
	"\x19DetectionTrackingPipeline\x12S\n" +
	"\x10SendDataToServer\x12\x1f.detection_tracking_system.Data\x1a\x1e.detection_tracking_system.Ack\x12Y\n" +
	"\x11SendFrameToServer\x12$.detection_tracking_system.FrameData\x1a\x1e.detection_tracking_system.Ack\x12a\n" +
	"\x15ReceiveDataFromServer\x12\x1f.detection_tracking_system.Data\x1a'.detection_tracking_system.DataResponse\x12R\n" +
	"\x0fCheckConnection\x12\x1f.detection_tracking_system.Data\x1a\x1e.detection_tracking_system.AckB5Z3github.com/etesami/detection-tracking-system/protocb\x06proto3"

var (
	file_detection_tracking_pipeline_proto_rawDescOnce sync.Once
	file_detection_tracking_pipeline_proto_rawDescData []byte
)

func file_detection_tracking_pipeline_proto_rawDescGZIP() []byte {
	file_detection_tracking_pipeline_proto_rawDescOnce.Do(func() {
		file_detection_tracking_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detection_tracking_pipeline_proto_rawDesc), len(file_detection_tracking_pipeline_proto_rawDesc)))
	})
	return file_detection_tracking_pipeline_proto_rawDescData
}

var file_detection_tracking_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_detection_tracking_pipeline_proto_goTypes = []any{
	(*Data)(nil),         // 0: detection_tracking_system.Data
	(*FrameData)(nil),    // 1: detection_tracking_system.FrameData
	(*DataResponse)(nil), // 2: detection_tracking_system.DataResponse
	(*Ack)(nil),          // 3: detection_tracking_system.Ack
}
var file_detection_tracking_pipeline_proto_depIdxs = []int32{
	0, // 0: detection_tracking_system.DetectionTrackingPipeline.SendDataToServer:input_type -> detection_tracking_system.Data
	1, // 1: detection_tracking_system.DetectionTrackingPipeline.SendFrameToServer:input_type -> detection_tracking_system.FrameData
	0, // 2: detection_tracking_system.DetectionTrackingPipeline.ReceiveDataFromServer:input_type -> detection_tracking_system.Data
	0, // 3: detection_tracking_system.DetectionTrackingPipeline.CheckConnection:input_type -> detection_tracking_system.Data
	3, // 4: detection_tracking_system.DetectionTrackingPipeline.SendDataToServer:output_type -> detection_tracking_system.Ack
	3, // 5: detection_tracking_system.DetectionTrackingPipeline.SendFrameToServer:output_type -> detection_tracking_system.Ack
	2, // 6: detection_tracking_system.DetectionTrackingPipeline.ReceiveDataFromServer:output_type -> detection_tracking_system.DataResponse
	3, // 7: detection_tracking_system.DetectionTrackingPipeline.CheckConnection:output_type -> detection_tracking_system.Ack
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_detection_tracking_pipeline_proto_init() }
func file_detection_tracking_pipeline_proto_init() {
	if File_detection_tracking_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detection_tracking_pipeline_proto_rawDesc), len(file_detection_tracking_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detection_tracking_pipeline_proto_goTypes,
		DependencyIndexes: file_detection_tracking_pipeline_proto_depIdxs,
		MessageInfos:      file_detection_tracking_pipeline_proto_msgTypes,
	}.Build()
	File_detection_tracking_pipeline_proto = out.File
	file_detection_tracking_pipeline_proto_goTypes = nil
	file_detection_tracking_pipeline_proto_depIdxs = nil
}
