# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection_tracking_pipeline.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'detection_tracking_pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!detection_tracking_pipeline.proto\x12\x19\x64\x65tection_tracking_system\"/\n\x04\x44\x61ta\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x16\n\x0esent_timestamp\x18\x02 \x01(\t\"c\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x1a\n\x12received_timestamp\x18\x03 \x01(\t\x12\x16\n\x0esent_timestamp\x18\x04 \x01(\t\"n\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1f\n\x17original_sent_timestamp\x18\x02 \x01(\t\x12\x1a\n\x12received_timestamp\x18\x03 \x01(\t\x12\x1a\n\x12\x61\x63k_sent_timestamp\x18\x04 \x01(\t2\xa7\x02\n\x19\x44\x65tectionTrackingPipeline\x12S\n\x10SendDataToServer\x12\x1f.detection_tracking_system.Data\x1a\x1e.detection_tracking_system.Ack\x12\x61\n\x15ReceiveDataFromServer\x12\x1f.detection_tracking_system.Data\x1a\'.detection_tracking_system.DataResponse\x12R\n\x0f\x43heckConnection\x12\x1f.detection_tracking_system.Data\x1a\x1e.detection_tracking_system.AckB5Z3github.com/etesami/detection-tracking-system/protocb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_tracking_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/etesami/detection-tracking-system/protoc'
  _globals['_DATA']._serialized_start=64
  _globals['_DATA']._serialized_end=111
  _globals['_DATARESPONSE']._serialized_start=113
  _globals['_DATARESPONSE']._serialized_end=212
  _globals['_ACK']._serialized_start=214
  _globals['_ACK']._serialized_end=324
  _globals['_DETECTIONTRACKINGPIPELINE']._serialized_start=327
  _globals['_DETECTIONTRACKINGPIPELINE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
