# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import detection_tracking_pipeline_pb2 as detection__tracking__pipeline__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in detection_tracking_pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectionTrackingPipelineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDataToServer = channel.unary_unary(
                '/detection_tracking_system.DetectionTrackingPipeline/SendDataToServer',
                request_serializer=detection__tracking__pipeline__pb2.Data.SerializeToString,
                response_deserializer=detection__tracking__pipeline__pb2.Ack.FromString,
                _registered_method=True)
        self.ReceiveDataFromServer = channel.unary_unary(
                '/detection_tracking_system.DetectionTrackingPipeline/ReceiveDataFromServer',
                request_serializer=detection__tracking__pipeline__pb2.Data.SerializeToString,
                response_deserializer=detection__tracking__pipeline__pb2.DataResponse.FromString,
                _registered_method=True)
        self.CheckConnection = channel.unary_unary(
                '/detection_tracking_system.DetectionTrackingPipeline/CheckConnection',
                request_serializer=detection__tracking__pipeline__pb2.Data.SerializeToString,
                response_deserializer=detection__tracking__pipeline__pb2.Ack.FromString,
                _registered_method=True)


class DetectionTrackingPipelineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDataToServer(self, request, context):
        """A simple RPC to send data to the server
        and receive an acknowledgment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveDataFromServer(self, request, context):
        """A simple RPC to request data from the local storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckConnection(self, request, context):
        """A simple RPC to send a ping to the service and receive a pong primarily for 
        testing the connection and latency
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionTrackingPipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDataToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDataToServer,
                    request_deserializer=detection__tracking__pipeline__pb2.Data.FromString,
                    response_serializer=detection__tracking__pipeline__pb2.Ack.SerializeToString,
            ),
            'ReceiveDataFromServer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveDataFromServer,
                    request_deserializer=detection__tracking__pipeline__pb2.Data.FromString,
                    response_serializer=detection__tracking__pipeline__pb2.DataResponse.SerializeToString,
            ),
            'CheckConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConnection,
                    request_deserializer=detection__tracking__pipeline__pb2.Data.FromString,
                    response_serializer=detection__tracking__pipeline__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detection_tracking_system.DetectionTrackingPipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('detection_tracking_system.DetectionTrackingPipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectionTrackingPipeline(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDataToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection_tracking_system.DetectionTrackingPipeline/SendDataToServer',
            detection__tracking__pipeline__pb2.Data.SerializeToString,
            detection__tracking__pipeline__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveDataFromServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection_tracking_system.DetectionTrackingPipeline/ReceiveDataFromServer',
            detection__tracking__pipeline__pb2.Data.SerializeToString,
            detection__tracking__pipeline__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection_tracking_system.DetectionTrackingPipeline/CheckConnection',
            detection__tracking__pipeline__pb2.Data.SerializeToString,
            detection__tracking__pipeline__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
