#!/bin/bash
# export UPDATE_FREQUENCY=5

export REMOTE_DETECTION_HOST=localhost
export REMOTE_DETECTION_PORT=5003

export REMOTE_TRACKER_HOST=localhost
export REMOTE_TRACKER_PORT=5004

export SVC_INGST_ADDR=localhost
export SVC_INGST_PORT=5002

export METRIC_ADDR=localhost
export METRIC_PORT=8002


export FRAME_RATE=5
export QUEUE_SIZE=180
export MAX_TOTAL_FRAMES=41
export DETECTION_FREQUENCY=5