#!/bin/bash
# export UPDATE_FREQUENCY=5

export REMOTE_TRACKING_HOST=localhost
export REMOTE_TRACKING_PORT=5003

export REMOTE_DETECTION_HOST=localhost
export REMOTE_DETECTION_PORT=5004

export SVC_INGST_ADDR=localhost
export SVC_INGST_PORT=5002

export METRIC_ADDR=localhost
export METRIC_PORT=8001